/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcul.h"

void *
calnull_1_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

long *
puiss_1_svc(struct Param *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */

	return &result;
}

long *
dec2bin_1_svc(int *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */

	return &result;
}
