/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calcul.h"
#include <stdio.h>

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
calnull_1(void *argp, CLIENT *clnt)
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, CALNULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

long *
puiss_1(struct Param *argp, CLIENT *clnt)
{
	static long clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, PUISS,
		(xdrproc_t) xdr_Param, (caddr_t) argp,
		(xdrproc_t) xdr_long, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

long *
dec2bin_1(int *argp, CLIENT *clnt)
{
	static long clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, DEC2BIN,
		(xdrproc_t) xdr_int, (caddr_t) argp,
		(xdrproc_t) xdr_long, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

int main(int argc, char *argv[]) {
    CLIENT *clnt;
    long int *result;
    Param p;
    int num;

    if (argc != 3) {
        printf("Usage: %s base exposant\n", argv[0]);
        return 1;
    }

    p.base = atoi(argv[1]);
    p.exposant = atoi(argv[2]);

    clnt = clnt_create("localhost", CAL_BIN_PROG, CAL_VERS_ONE, "tcp");
    if (clnt == NULL) {
        clnt_pcreateerror("Erreur de connexion au serveur");
        return 1;
    }

    result = puiss_1(&p, clnt);
    if (result == NULL) {
        clnt_perror(clnt, "Appel distant échoué");
        return 1;
    }
    printf("Résultat de %d^%d = %ld\n", p.base, p.exposant, *result);

    clnt_destroy(clnt);
    return 0;
} 